### ISSUE TITLE
java.io.FileNotFoundException: ..\snapshots\snapshot-hourly_2017-04-13t18:01:00.002z (The filename, directory name, or volume label syntax is incorrect)

### ISSUE THREAD

**Issue by tommytusj** [enonic/app-snapshotter#1]
Running with default configuration on Windows 10 64bit and XP 6.9.2

java.io.FileNotFoundException: C:\Users\xxxxx\Downloads\distro-6.9.2\enonic-xp-6.9.2\home\snapshots\snapshot-hourly_2017-04-13t18:01:00.002z (The filename, directory name, or volume label syntax is incorrect)

Any clues? Running XP as administrator and Data Toolbox app can successfully create snapshots so I don't think it has anything to do with user rights on windows. 
[stacktrace.txt](https://github.com/enonic/app-snapshotter/files/920463/stacktrace.txt)

**Comment by runarmyklebust** [comment]
Hmm, is it possible to create a file with the same name in the same folder?

**Comment by tommytusj** [comment]
Yes, colon is illegal on Windows https://msdn.microsoft.com/en-us/library/aa365247

**Comment by tommytusj** [comment]
any news on this issue? :)

**Comment by runarmyklebust** [comment]
Can you try the new version 1.0.5 from market? Needs xp v6.10.2 though, is that a problem?

**Comment by tommytusj** [comment]
I'll try it. We're running 6.10.2 in test :)

**Comment by tommytusj** [comment]
Seems to be working fine now, at least the one running every hour. I can report back on monday how it went
